version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: "@types/sharp"
    versions:
    - 0.27.1
    - 0.27.2
    - 0.27.3
  - dependency-name: sharp
    versions:
    - 0.27.1
    - 0.27.2
    - 0.28.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@types/cors"
    versions:
    - 2.8.10
    - 2.8.9
  - dependency-name: "@types/passport"
    versions:
    - 1.0.5
    - 1.0.6
  - dependency-name: "@types/express-fileupload"
    versions:
    - 1.1.6
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: uuid
    versions:
    - 8.3.2
  - dependency-name: "@types/cookie-session"
    versions:
    - 2.0.42
