variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - qa
  - build
  - deploy

sonarcloud-check:
  stage: qa
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop

include:
  stage: qa
  template: Dependency-Scanning.gitlab-ci.yml

include:
  stage: qa
  template: SAST.gitlab-ci.yml

build:
  stage: build
  image: node:13.1.0
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  cache:
    paths:
      - node_modules/
      - .yarn
  only:
    - master
  script:
    - npm run build