variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - test
  - build
  - deploy

sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop

include:
  stage: test
  template: Dependency-Scanning.gitlab-ci.yml

include:
  stage: test
  template: SAST.gitlab-ci.yml

build:
  stage: build
  image: node:13.1.0
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  cache:
    paths:
      - node_modules/
      - .yarn
  only:
    - master
  script:
    - yarn run build

deploy:
  stage: deploy
  image: node:13.1.0
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
    - yarn run build
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  cache:
    paths:
      - node_modules/
      - .yarn
  artifacts:
    paths:
      - lib/
  only:
    - master
  script:
    - ssh-add <(echo "$PROD_KEY")
    - scp -P22 -r lib/* $PROD_USER@$PROD_HOST:v2/api/