variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

stages:
  - test
  - build
  - deploy
  - notification

include:
  stage: test
  template: Dependency-Scanning.gitlab-ci.yml

sonarcloud-check:
  stage: test
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop

build:
  stage: build
  image: node:13.1.0
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  cache:
    paths:
      - node_modules/
      - .yarn
  artifacts:
    paths:
      - lib/
  script:
    - echo "Building"
    - yarn run build

staging:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  image: node:13.1.0
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$STAGING_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $STAGING_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  only:
    - master
  script:
    - echo "Uploading build artifacts"
    - scp -P22 -r package.json $STAGING_USER@$STAGING_HOST:$CI_PROJECT_TITLE
    - scp -P22 -r yarn.lock $STAGING_USER@$STAGING_HOST:$CI_PROJECT_TITLE
    - scp -P22 -r lib/* $STAGING_USER@$STAGING_HOST:$CI_PROJECT_TITLE/lib
    - scp -P22 -r scripts/* $STAGING_USER@$STAGING_HOST:$CI_PROJECT_TITLE/scripts
    - scp -P22 -r migrations/* $STAGING_USER@$STAGING_HOST:$CI_PROJECT_TITLE/migrations
    - ssh -p22 $STAGING_USER@$STAGING_HOST "cd $CI_PROJECT_TITLE && yarn install && yarn migrate"
    - ssh -p22 $STAGING_USER@$STAGING_HOST "sudo pm2 restart $CI_PROJECT_TITLE"


deploy_prod:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  image: node:13.5.0
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$PROD_SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $PROD_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  only:
    - master
  script:
    - echo "Uploading build artifacts"
    - scp -P22 -r package.json $PROD_USER@$PROD_HOST:$CI_PROJECT_NAMESPACE/$CI_PROJECT_TITLE
    - scp -P22 -r yarn.lock $PROD_USER@$PROD_HOST:$CI_PROJECT_NAMESPACE/$CI_PROJECT_TITLE
    - scp -P22 -r lib/* $PROD_USER@$PROD_HOST:$CI_PROJECT_NAMESPACE/$CI_PROJECT_TITLE/lib
    - scp -P22 -r scripts/* $PROD_USER@$PROD_HOST:$CI_PROJECT_NAMESPACE/$CI_PROJECT_TITLE/scripts
    - scp -P22 -r migrations/* $PROD_USER@$PROD_HOST:$CI_PROJECT_NAMESPACE/$CI_PROJECT_TITLE/migrations
    - ssh -p22 $PROD_USER@$PROD_HOST "cd $CI_PROJECT_NAMESPACE/$CI_PROJECT_TITLE && yarn install && yarn migrate"
    - ssh -p22 $PROD_USER@$PROD_HOST "sudo pm2 restart $CI_PROJECT_TITLE"

success_notification:
  stage: notification
  script:
    - echo "Success notification"
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
  when: on_success
failure_notification:
  stage: notification
  script:
    - echo "Failure notification"
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL
  when: on_failure
